### PR TITLE
Development branch - Apple.com Page Clone

### PR DESCRIPTION
**Pull request by AdedayoOpeyemi**
This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of old an old version of the Apple website webpage.

You can find the original project specification at: https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-backgrounds-and-gradients

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @AdedayoOpeyemi      
#### Great Job so far, but there are a few more things required. 
### General
- [ ] This four elements should be links 

- Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
- Please fix the horizontal scroll
- Let the search input look more like the original


### Make changes and submit another code review request.
*Happy coding*

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work! @AdedayoOpeyemi :rocket: 
Your project is really coming together nicely :ok_hand: Please consider my comments below, make the appropriate changes and request another review. I wish you all the best and see you at the very top :medal_military: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @AdedayoOpeyemi, **congratulations** on fixing the changes requested by the previous reviewers 👍 . I, therefore, approve your project 😄 Go ahead and merge to master and submit a project completion form. Good luck with your next submissions 👨‍💻 
[OPTIONAL]
Kindly fix the width of the search input on the nav by reducing the width. Thanks 👍 

_Happy coding_
@slack on **Daniel Larbi Addo**

**Pull request merged**
